List<String> PermissionData = [
  'Access Passwords',
  'Access Whatsapp Data',
  'Access Camera in background process',
  'Can change Phone Settings',
  'Read all your Contacts',
  'Record Phone Calls',
  'Read Call Logs',
  'Access your Real-time Location Data',
  'Record Audio',
  'Read SMS',
  'Can read your Transactions',
  'Use your Bio-Metrics',
  'Reads your Calender Data',
  // 'Can Automatic Delete any Data',
  // 'Get all your accounts ID and Password',
  // 'Read Outgoing Call',
];